<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
class RegencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
        // Implementasi seeding untuk data kabupaten dan kota
    public function run(): void
    {
        $regencies = [
            // Provinsi Aceh (province_id = 1)
            ['name' => 'Kabupaten Aceh Barat', 'code' => 'KAB_ACEH_BARAT', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Barat Daya', 'code' => 'KAB_ACEH_BARAT_DAYA', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Besar', 'code' => 'KAB_ACEH_BESAR', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Jaya', 'code' => 'KAB_ACEH_JAYA', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Selatan', 'code' => 'KAB_ACEH_SELATAN', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Singkil', 'code' => 'KAB_ACEH_SINGKIL', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Tamiang', 'code' => 'KAB_ACEH_TAMIANG', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Tengah', 'code' => 'KAB_ACEH_TENGAH', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Tenggara', 'code' => 'KAB_ACEH_TENGGARA', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Timur', 'code' => 'KAB_ACEH_TIMUR', 'province_id' => 1],
            ['name' => 'Kabupaten Aceh Utara', 'code' => 'KAB_ACEH_UTARA', 'province_id' => 1],
            ['name' => 'Kabupaten Bener Meriah', 'code' => 'KAB_BENER_MERIAH', 'province_id' => 1],
            ['name' => 'Kabupaten Bireuen', 'code' => 'KAB_BIREUEN', 'province_id' => 1],
            ['name' => 'Kabupaten Gayo Lues', 'code' => 'KAB_GAYO_LUES', 'province_id' => 1],
            ['name' => 'Kabupaten Nagan Raya', 'code' => 'KAB_NAGAN_RAYA', 'province_id' => 1],
            ['name' => 'Kabupaten Pidie', 'code' => 'KAB_PIDIE', 'province_id' => 1],
            ['name' => 'Kabupaten Pidie Jaya', 'code' => 'KAB_PIDIE_JAYA', 'province_id' => 1],
            ['name' => 'Kabupaten Simeulue', 'code' => 'KAB_SIMEULUE', 'province_id' => 1],
            ['name' => 'Kota Banda Aceh', 'code' => 'KOTA_BANDA_ACEH', 'province_id' => 1],
            ['name' => 'Kota Langsa', 'code' => 'KOTA_LANGSA', 'province_id' => 1],
            ['name' => 'Kota Lhoksekamawe', 'code' => 'KOTA_LHOKSEKAMAWE', 'province_id' => 1],
            ['name' => 'Kota Sabang', 'code' => 'KOTA_SABANG', 'province_id' => 1],
            ['name' => 'Kota Subulussalam', 'code' => 'KOTA_SUBULUSSALAM', 'province_id' => 1],
            
            // Provinsi Sumatera Utara (province_id = 2)
            ['name' => 'Kabupaten Asahan', 'code' => 'KAB_ASAHAN', 'province_id' => 2],
            ['name' => 'Kabupaten Batubara', 'code' => 'KAB_BATUBARA', 'province_id' => 2],
            ['name' => 'Kabupaten Dairi', 'code' => 'KAB_DAIRI', 'province_id' => 2],
            ['name' => 'Kabupaten Deli Serdang', 'code' => 'KAB_DELI_SERDANG', 'province_id' => 2],
            ['name' => 'Kabupaten Humbang Hasundutan', 'code' => 'KAB_HUMBANG_HASUNDUTAN', 'province_id' => 2],
            ['name' => 'Kabupaten Karo', 'code' => 'KAB_KARO', 'province_id' => 2],
            ['name' => 'Kabupaten Labuhanbatu', 'code' => 'KAB_LABUHANBATU', 'province_id' => 2],
            ['name' => 'Kabupaten Labuhanbatu Selatan', 'code' => 'KAB_LABUHANBATU_SELATAN', 'province_id' => 2],
            ['name' => 'Kabupaten Labuhanbatu Utara', 'code' => 'KAB_LABUHANBATU_UTARA', 'province_id' => 2],
            ['name' => 'Kabupaten Langkat', 'code' => 'KAB_LANGKAT', 'province_id' => 2],
            ['name' => 'Kabupaten Mandailing Natal', 'code' => 'KAB_MANDAILING_NATAL', 'province_id' => 2],
            ['name' => 'Kabupaten Nias', 'code' => 'KAB_NIAS', 'province_id' => 2],
            ['name' => 'Kabupaten Nias Barat', 'code' => 'KAB_NIAS_BARAT', 'province_id' => 2],
            ['name' => 'Kabupaten Nias Selatan', 'code' => 'KAB_NIAS_SELATAN', 'province_id' => 2],
            ['name' => 'Kabupaten Nias Utara', 'code' => 'KAB_NIAS_UTARA', 'province_id' => 2],
            ['name' => 'Kabupaten Padang Lawas', 'code' => 'KAB_PADANG_LAWAS', 'province_id' => 2],
            ['name' => 'Kabupaten Padang Lawas Utara', 'code' => 'KAB_PADANG_LAWAS_UTARA', 'province_id' => 2],
            ['name' => 'Kabupaten Pakpak Bharat', 'code' => 'KAB_PAKPAK_BHARAT', 'province_id' => 2],
            ['name' => 'Kabupaten Samosir', 'code' => 'KAB_SAMOSIR', 'province_id' => 2],
            ['name' => 'Kabupaten Serdang Bedagai', 'code' => 'KAB_SERDANG_BEDAGAI', 'province_id' => 2],
            ['name' => 'Kabupaten Simalungun', 'code' => 'KAB_SIMALUNGUN', 'province_id' => 2],
            ['name' => 'Kabupaten Tapanuli Selatan', 'code' => 'KAB_TAPANULI_SELATAN', 'province_id' => 2],
            ['name' => 'Kabupaten Tapanuli Tengah', 'code' => 'KAB_TAPANULI_TENGAH', 'province_id' => 2],
            ['name' => 'Kabupaten Tapanuli Utara', 'code' => 'KAB_TAPANULI_UTARA', 'province_id' => 2],
            ['name' => 'Kabupaten Toba Samosir', 'code' => 'KAB_TOBA_SAMOSIR', 'province_id' => 2],
            ['name' => 'Kota Binjai', 'code' => 'KOTA_BINJAI', 'province_id' => 2],
            ['name' => 'Kota Gunungsitoli', 'code' => 'KOTA_GUNUNGSITOLI', 'province_id' => 2],
            ['name' => 'Kota Medan', 'code' => 'KOTA_MEDAN', 'province_id' => 2],
            ['name' => 'Kota Padangsidempuan', 'code' => 'KOTA_PADANGSIDEMPUAN', 'province_id' => 2],
            ['name' => 'Kota Pematangsiantar', 'code' => 'KOTA_PEMATANGSIANTAR', 'province_id' => 2],
            ['name' => 'Kota Sibolga', 'code' => 'KOTA_SIBOLGA', 'province_id' => 2],
            ['name' => 'Kota Tanjungbalai', 'code' => 'KOTA_TANJUNGBALAI', 'province_id' => 2],
            ['name' => 'Kota Tebing Tinggi', 'code' => 'KOTA_TEBING_TINGGI', 'province_id' => 2],
            
            // Provinsi Sumatera Barat (province_id = 3)
            ['name' => 'Kabupaten Agam', 'code' => 'KAB_AGAM', 'province_id' => 3],
            ['name' => 'Kabupaten Dharmasraya', 'code' => 'KAB_DHARMASRAYA', 'province_id' => 3],
            ['name' => 'Kabupaten Kepulauan Mentawai', 'code' => 'KAB_KEPULAUAN_MENTAWAI', 'province_id' => 3],
            ['name' => 'Kabupaten Lima Puluh Kota', 'code' => 'KAB_LIMA_PULUH_KOTA', 'province_id' => 3],
            ['name' => 'Kabupaten Padang Pariaman', 'code' => 'KAB_PADANG_PARIAMAN', 'province_id' => 3],
            ['name' => 'Kabupaten Pasaman', 'code' => 'KAB_PASAMAN', 'province_id' => 3],
            ['name' => 'Kabupaten Pasaman Barat', 'code' => 'KAB_PASAMAN_BARAT', 'province_id' => 3],
            ['name' => 'Kabupaten Pesisir Selatan', 'code' => 'KAB_PESISIR_SELATAN', 'province_id' => 3],
            ['name' => 'Kabupaten Sijunjung', 'code' => 'KAB_SIJUNJUNG', 'province_id' => 3],
            ['name' => 'Kabupaten Solok', 'code' => 'KAB_SOLOK', 'province_id' => 3],
            ['name' => 'Kabupaten Solok Selatan', 'code' => 'KAB_SOLOK_SELATAN', 'province_id' => 3],
            ['name' => 'Kabupaten Tanah Datar', 'code' => 'KAB_TANAH_DATAR', 'province_id' => 3],
            ['name' => 'Kota Bukittinggi', 'code' => 'KOTA_BUKITTINGGI', 'province_id' => 3],
            ['name' => 'Kota Padang', 'code' => 'KOTA_PADANG', 'province_id' => 3],
            ['name' => 'Kota Padangpanjang', 'code' => 'KOTA_PADANGPANJANG', 'province_id' => 3],
            ['name' => 'Kota Pariaman', 'code' => 'KOTA_PARIAMAN', 'province_id' => 3],
            ['name' => 'Kota Payakumbuh', 'code' => 'KOTA_PAYAKUMBUH', 'province_id' => 3],
            ['name' => 'Kota Sawahlunto', 'code' => 'KOTA_SAWAHLUNTO', 'province_id' => 3],
            ['name' => 'Kota Solok', 'code' => 'KOTA_SOLOK', 'province_id' => 3],
            
            // Provinsi Sumatera Selatan (province_id = 4)
            ['name' => 'Kabupaten Banyuasin', 'code' => 'KAB_BANYUASIN', 'province_id' => 4],
            ['name' => 'Kabupaten Empat Lawang', 'code' => 'KAB_EMPAT_LAWANG', 'province_id' => 4],
            ['name' => 'Kabupaten Lahat', 'code' => 'KAB_LAHAT', 'province_id' => 4],
            ['name' => 'Kabupaten Muara Enim', 'code' => 'KAB_MUARA_ENIM', 'province_id' => 4],
            ['name' => 'Kabupaten Musi Banyuasin', 'code' => 'KAB_MUSI_BANYUASIN', 'province_id' => 4],
            ['name' => 'Kabupaten Musi Rawas', 'code' => 'KAB_MUSI_RAWAS', 'province_id' => 4],
            ['name' => 'Kabupaten Musi Rawas Utara', 'code' => 'KAB_MUSI_RAWAS_UTARA', 'province_id' => 4],
            ['name' => 'Kabupaten Ogan Ilir', 'code' => 'KAB_OGAN_ILIR', 'province_id' => 4],
            ['name' => 'Kabupaten Ogan Komering Ilir', 'code' => 'KAB_OGAN_KOMERING_ILIR', 'province_id' => 4],
            ['name' => 'Kabupaten Ogan Komering Ulu', 'code' => 'KAB_OGAN_KOMERING_ULU', 'province_id' => 4],
            ['name' => 'Kabupaten Ogan Komering Ulu Selatan', 'code' => 'KAB_OGAN_KOMERING_ULU_SELATAN', 'province_id' => 4],
            ['name' => 'Kabupaten Ogan Komering Ulu Timur', 'code' => 'KAB_OGAN_KOMERING_ULU_TIMUR', 'province_id' => 4],
            ['name' => 'Kabupaten Penukal Abab Lematang Ilir', 'code' => 'KAB_PENUKAL_ABAB', 'province_id' => 4],
            ['name' => 'Kota Lubuklinggau', 'code' => 'KOTA_LUBUKLINGGAU', 'province_id' => 4],
            ['name' => 'Kota Pagar Alam', 'code' => 'KOTA_PAGAR_ALAM', 'province_id' => 4],
            ['name' => 'Kota Palembang', 'code' => 'KOTA_PALEMBANG', 'province_id' => 4],
            ['name' => 'Kota Prabumulih', 'code' => 'KOTA_PRABUMULIH', 'province_id' => 4],
            
            // Provinsi Riau (province_id = 5)
            ['name' => 'Kabupaten Bengkalis', 'code' => 'KAB_BENGKALIS', 'province_id' => 5],
            ['name' => 'Kabupaten Indragiri Hilir', 'code' => 'KAB_INDRAGIRI_HILIR', 'province_id' => 5],
            ['name' => 'Kabupaten Indragiri Hulu', 'code' => 'KAB_INDRAGIRI_HULU', 'province_id' => 5],
            ['name' => 'Kabupaten Kampar', 'code' => 'KAB_KAMPAR', 'province_id' => 5],
            ['name' => 'Kabupaten Kepulauan Meranti', 'code' => 'KAB_KEPULAUAN_MERANTI', 'province_id' => 5],
            ['name' => 'Kabupaten Kuantan Singingi', 'code' => 'KAB_KUANTAN_SINGINGI', 'province_id' => 5],
            ['name' => 'Kabupaten Pelalawan', 'code' => 'KAB_PELALAWAN', 'province_id' => 5],
            ['name' => 'Kabupaten Rokan Hilir', 'code' => 'KAB_ROKAN_HILIR', 'province_id' => 5],
            ['name' => 'Kabupaten Rokan Hulu', 'code' => 'KAB_ROKAN_HULU', 'province_id' => 5],
            ['name' => 'Kabupaten Siak', 'code' => 'KAB_SIAK', 'province_id' => 5],
            ['name' => 'Kota Dumai', 'code' => 'KOTA_DUMAI', 'province_id' => 5],
            ['name' => 'Kota Pekanbaru', 'code' => 'KOTA_PEKANBARU', 'province_id' => 5],
            
            // Provinsi Kepulauan Riau (province_id = 6)
            ['name' => 'Kabupaten Bintan', 'code' => 'KAB_BINTAN', 'province_id' => 6],
            ['name' => 'Kabupaten Karimun', 'code' => 'KAB_KARIMUN', 'province_id' => 6],
            ['name' => 'Kabupaten Kepulauan Anambas', 'code' => 'KAB_KEPULAUAN_ANAMBAS', 'province_id' => 6],
            ['name' => 'Kabupaten Lingga', 'code' => 'KAB_LINGGA', 'province_id' => 6],
            ['name' => 'Kabupaten Natuna', 'code' => 'KAB_NATUNA', 'province_id' => 6],
            ['name' => 'Kota Batam', 'code' => 'KOTA_BATAM', 'province_id' => 6],
            ['name' => 'Kota Tanjung Pinang', 'code' => 'KOTA_TANJUNG_PINANG', 'province_id' => 6],
            
            // Provinsi Jambi (province_id = 7)
            ['name' => 'Kabupaten Batanghari', 'code' => 'KAB_BATANGHARI', 'province_id' => 7],
            ['name' => 'Kabupaten Bungo', 'code' => 'KAB_BUNGO', 'province_id' => 7],
            ['name' => 'Kabupaten Kerinci', 'code' => 'KAB_KERINCI', 'province_id' => 7],
            ['name' => 'Kabupaten Merangin', 'code' => 'KAB_MERANGIN', 'province_id' => 7],
            ['name' => 'Kabupaten Muaro Jambi', 'code' => 'KAB_MUARO_JAMBI', 'province_id' => 7],
            ['name' => 'Kabupaten Sarolangun', 'code' => 'KAB_SAROLANGUN', 'province_id' => 7],
            ['name' => 'Kabupaten Tanjung Jabung Barat', 'code' => 'KAB_TANJUNG_JABUNG_BARAT', 'province_id' => 7],
            ['name' => 'Kabupaten Tanjung Jabung Timur', 'code' => 'KAB_TANJUNG_JABUNG_TIMUR', 'province_id' => 7],
            ['name' => 'Kabupaten Tebo', 'code' => 'KAB_TEBO', 'province_id' => 7],
            ['name' => 'Kota Jambi', 'code' => 'KOTA_JAMBI', 'province_id' => 7],
            ['name' => 'Kota Sungai Penuh', 'code' => 'KOTA_SUNGAI_PENUH', 'province_id' => 7],
            
            // Provinsi Bengkulu (province_id = 8)
            ['name' => 'Kabupaten Bengkulu Selatan', 'code' => 'KAB_BENGKULU_SELATAN', 'province_id' => 8],
            ['name' => 'Kabupaten Bengkulu Tengah', 'code' => 'KAB_BENGKULU_TENGAH', 'province_id' => 8],
            ['name' => 'Kabupaten Bengkulu Utara', 'code' => 'KAB_BENGKULU_UTARA', 'province_id' => 8],
            ['name' => 'Kabupaten Kaur', 'code' => 'KAB_KAUR', 'province_id' => 8],
            ['name' => 'Kabupaten Kepahiang', 'code' => 'KAB_KEPAHIANG', 'province_id' => 8],
            ['name' => 'Kabupaten Lebong', 'code' => 'KAB_LEBONG', 'province_id' => 8],
            ['name' => 'Kabupaten Mukomuko', 'code' => 'KAB_MUKOMUKO', 'province_id' => 8],
            ['name' => 'Kabupaten Rejang Lebong', 'code' => 'KAB_REJANG_LEBONG', 'province_id' => 8],
            ['name' => 'Kabupaten Seluma', 'code' => 'KAB_SELUMA', 'province_id' => 8],
            ['name' => 'Kota Bengkulu', 'code' => 'KOTA_BENGKULU', 'province_id' => 8],
            
            // Provinsi Bangka Belitung (province_id = 9)
            ['name' => 'Kabupaten Bangka', 'code' => 'KAB_BANGKA', 'province_id' => 9],
            ['name' => 'Kabupaten Bangka Barat', 'code' => 'KAB_BANGKA_BARAT', 'province_id' => 9],
            ['name' => 'Kabupaten Bangka Selatan', 'code' => 'KAB_BANGKA_SELATAN', 'province_id' => 9],
            ['name' => 'Kabupaten Bangka Tengah', 'code' => 'KAB_BANGKA_TENGAH', 'province_id' => 9],
            ['name' => 'Kabupaten Belitung', 'code' => 'KAB_BELITUNG', 'province_id' => 9],
            ['name' => 'Kabupaten Belitung Timur', 'code' => 'KAB_BELITUNG_TIMUR', 'province_id' => 9],
            ['name' => 'Kota Pangkal Pinang', 'code' => 'KOTA_PANGKAL_PINANG', 'province_id' => 9],
            
            // Provinsi Lampung (province_id = 10)
            ['name' => 'Kabupaten Lampung Tengah', 'code' => 'KAB_LAMPUNG_TENGAH', 'province_id' => 10],
            ['name' => 'Kabupaten Lampung Utara', 'code' => 'KAB_LAMPUNG_UTARA', 'province_id' => 10],
            ['name' => 'Kabupaten Lampung Selatan', 'code' => 'KAB_LAMPUNG_SELATAN', 'province_id' => 10],
            ['name' => 'Kabupaten Lampung Barat', 'code' => 'KAB_LAMPUNG_BARAT', 'province_id' => 10],
            ['name' => 'Kabupaten Lampung Timur', 'code' => 'KAB_LAMPUNG_TIMUR', 'province_id' => 10],
            ['name' => 'Kabupaten Mesuji', 'code' => 'KAB_MESUJI', 'province_id' => 10],
            ['name' => 'Kabupaten Pesawaran', 'code' => 'KAB_PESAWARAN', 'province_id' => 10],
            ['name' => 'Kabupaten Pesisir Barat', 'code' => 'KAB_PESISIR_BARAT', 'province_id' => 10],
            ['name' => 'Kabupaten Pringsewu', 'code' => 'KAB_PRINGSEWU', 'province_id' => 10],
            ['name' => 'Kabupaten Tulang Bawang', 'code' => 'KAB_TULANG_BAWANG', 'province_id' => 10],
            ['name' => 'Kabupaten Tulang Bawang Barat', 'code' => 'KAB_TULANG_BAWANG_BARAT', 'province_id' => 10],
            ['name' => 'Kabupaten Tanggamus', 'code' => 'KAB_TANGGAMUS', 'province_id' => 10],
            ['name' => 'Kabupaten Way Kanan', 'code' => 'KAB_WAY_KANAN', 'province_id' => 10],
            ['name' => 'Kota Bandar Lampung', 'code' => 'KOTA_BANDAR_LAMPUNG', 'province_id' => 10],
            ['name' => 'Kota Metro', 'code' => 'KOTA_METRO', 'province_id' => 10],
            
            // Provinsi Banten (province_id = 11)
            ['name' => 'Kabupaten Lebak', 'code' => 'KAB_LEBAK', 'province_id' => 11],
            ['name' => 'Kabupaten Pandeglang', 'code' => 'KAB_PANDEGLANG', 'province_id' => 11],
            ['name' => 'Kabupaten Serang', 'code' => 'KAB_SERANG', 'province_id' => 11],
            ['name' => 'Kabupaten Tangerang', 'code' => 'KAB_TANGERANG', 'province_id' => 11],
            ['name' => 'Kota Cilegon', 'code' => 'KOTA_CILEGON', 'province_id' => 11],
            ['name' => 'Kota Serang', 'code' => 'KOTA_SERANG', 'province_id' => 11],
            ['name' => 'Kota Tangerang', 'code' => 'KOTA_TANGERANG', 'province_id' => 11],
            ['name' => 'Kota Tangerang Selatan', 'code' => 'KOTA_TANGERANG_SELATAN', 'province_id' => 11],
            
            // Provinsi Jawa Barat (province_id = 12)
            ['name' => 'Kabupaten Bandung', 'code' => 'KAB_BANDUNG', 'province_id' => 12],
            ['name' => 'Kabupaten Bandung Barat', 'code' => 'KAB_BANDUNG_BARAT', 'province_id' => 12],
            ['name' => 'Kabupaten Bekasi', 'code' => 'KAB_BEKASI', 'province_id' => 12],
            ['name' => 'Kabupaten Bogor', 'code' => 'KAB_BOGOR', 'province_id' => 12],
            ['name' => 'Kabupaten Ciamis', 'code' => 'KAB_CIAMIS', 'province_id' => 12],
            ['name' => 'Kabupaten Cianjur', 'code' => 'KAB_CIANJUR', 'province_id' => 12],
            ['name' => 'Kabupaten Cirebon', 'code' => 'KAB_CIREBON', 'province_id' => 12],
            ['name' => 'Kabupaten Garut', 'code' => 'KAB_GARUT', 'province_id' => 12],
            ['name' => 'Kabupaten Indramayu', 'code' => 'KAB_INDRAMAYU', 'province_id' => 12],
            ['name' => 'Kabupaten Karawang', 'code' => 'KAB_KARAWANG', 'province_id' => 12],
            ['name' => 'Kabupaten Kuningan', 'code' => 'KAB_KUNINGAN', 'province_id' => 12],
            ['name' => 'Kabupaten Majalengka', 'code' => 'KAB_MAJALENGKA', 'province_id' => 12],
            ['name' => 'Kabupaten Pangandaran', 'code' => 'KAB_PANGANDARAN', 'province_id' => 12],
            ['name' => 'Kabupaten Purwakarta', 'code' => 'KAB_PURWAKARTA', 'province_id' => 12],
            ['name' => 'Kabupaten Subang', 'code' => 'KAB_SUBANG', 'province_id' => 12],
            ['name' => 'Kabupaten Sukabumi', 'code' => 'KAB_SUKABUMI', 'province_id' => 12],
            ['name' => 'Kabupaten Sumedang', 'code' => 'KAB_SUMEDANG', 'province_id' => 12],
            ['name' => 'Kabupaten Tasikmalaya', 'code' => 'KAB_TASIKMALAYA', 'province_id' => 12],
            ['name' => 'Kota Bandung', 'code' => 'KOTA_BANDUNG', 'province_id' => 12],
            ['name' => 'Kota Banjar', 'code' => 'KOTA_BANJAR', 'province_id' => 12],
            ['name' => 'Kota Bekasi', 'code' => 'KOTA_BEKASI', 'province_id' => 12],
            ['name' => 'Kota Bogor', 'code' => 'KOTA_BOGOR', 'province_id' => 12],
            ['name' => 'Kota Cimahi', 'code' => 'KOTA_CIMAHI', 'province_id' => 12],
            ['name' => 'Kota Cirebon', 'code' => 'KOTA_CIREBON', 'province_id' => 12],
            ['name' => 'Kota Depok', 'code' => 'KOTA_DEPOK', 'province_id' => 12],
            ['name' => 'Kota Sukabumi', 'code' => 'KOTA_SUKABUMI', 'province_id' => 12],
            ['name' => 'Kota Tasikmalaya', 'code' => 'KOTA_TASIKMALAYA', 'province_id' => 12],
            
            // Provinsi Jawa Tengah (province_id = 13)
            ['name' => 'Kabupaten Banjarnegara', 'code' => 'KAB_BANJARNEGARA', 'province_id' => 13],
            ['name' => 'Kabupaten Banyumas', 'code' => 'KAB_BANYUMAS', 'province_id' => 13],
            ['name' => 'Kabupaten Batang', 'code' => 'KAB_BATANG', 'province_id' => 13],
            ['name' => 'Kabupaten Blora', 'code' => 'KAB_BLORA', 'province_id' => 13],
            ['name' => 'Kabupaten Boyolali', 'code' => 'KAB_BOYOLALI', 'province_id' => 13],
            ['name' => 'Kabupaten Brebes', 'code' => 'KAB_BREBES', 'province_id' => 13],
            ['name' => 'Kabupaten Cilacap', 'code' => 'KAB_CILACAP', 'province_id' => 13],
            ['name' => 'Kabupaten Demak', 'code' => 'KAB_DEMAK', 'province_id' => 13],
            ['name' => 'Kabupaten Grobogan', 'code' => 'KAB_GROBOGAN', 'province_id' => 13],
            ['name' => 'Kabupaten Jepara', 'code' => 'KAB_JEPARA', 'province_id' => 13],
            ['name' => 'Kabupaten Karanganyar', 'code' => 'KAB_KARANGANYAR', 'province_id' => 13],
            ['name' => 'Kabupaten Kebumen', 'code' => 'KAB_KEBUMEN', 'province_id' => 13],
            ['name' => 'Kabupaten Kendal', 'code' => 'KAB_KENDAL', 'province_id' => 13],
            ['name' => 'Kabupaten Klaten', 'code' => 'KAB_KLATEN', 'province_id' => 13],
            ['name' => 'Kabupaten Kudus', 'code' => 'KAB_KUDUS', 'province_id' => 13],
            ['name' => 'Kabupaten Magelang', 'code' => 'KAB_MAGELANG', 'province_id' => 13],
            ['name' => 'Kabupaten Pati', 'code' => 'KAB_PATI', 'province_id' => 13],
            ['name' => 'Kabupaten Pekalongan', 'code' => 'KAB_PEKALONGAN', 'province_id' => 13],
            ['name' => 'Kabupaten Pemalang', 'code' => 'KAB_PEMALANG', 'province_id' => 13],
            ['name' => 'Kabupaten Purbalingga', 'code' => 'KAB_PURBALINGGA', 'province_id' => 13],
            ['name' => 'Kabupaten Purworejo', 'code' => 'KAB_PURWOREJO', 'province_id' => 13],
            ['name' => 'Kabupaten Rembang', 'code' => 'KAB_REMBANG', 'province_id' => 13],
            ['name' => 'Kabupaten Semarang', 'code' => 'KAB_SEMARANG', 'province_id' => 13],
            ['name' => 'Kabupaten Sragen', 'code' => 'KAB_SRAGEN', 'province_id' => 13],
            ['name' => 'Kabupaten Sukoharjo', 'code' => 'KAB_SUKOHARJO', 'province_id' => 13],
            ['name' => 'Kabupaten Tegal', 'code' => 'KAB_TEGAL', 'province_id' => 13],
            ['name' => 'Kabupaten Temanggung', 'code' => 'KAB_TEMANGGUNG', 'province_id' => 13],
            ['name' => 'Kabupaten Wonogiri', 'code' => 'KAB_WONOGIRI', 'province_id' => 13],
            ['name' => 'Kabupaten Wonosobo', 'code' => 'KAB_WONOSOBO', 'province_id' => 13],
            ['name' => 'Kota Magelang', 'code' => 'KOTA_MAGELANG', 'province_id' => 13],
            ['name' => 'Kota Pekalongan', 'code' => 'KOTA_PEKALONGAN', 'province_id' => 13],
            ['name' => 'Kota Salatiga', 'code' => 'KOTA_SALATIGA', 'province_id' => 13],
            ['name' => 'Kota Semarang', 'code' => 'KOTA_SEMARANG', 'province_id' => 13],
            ['name' => 'Kota Surakarta', 'code' => 'KOTA_SURAKARTA', 'province_id' => 13],
            ['name' => 'Kota Tegal', 'code' => 'KOTA_TEGAL', 'province_id' => 13],
            
            // Provinsi Jawa Timur (province_id = 14)
            ['name' => 'Kabupaten Bangkalan', 'code' => 'KAB_BANGKALAN', 'province_id' => 14],
            ['name' => 'Kabupaten Banyuwangi', 'code' => 'KAB_BANYUWANGI', 'province_id' => 14],
            ['name' => 'Kabupaten Blitar', 'code' => 'KAB_BLITAR', 'province_id' => 14],
            ['name' => 'Kabupaten Bojonegoro', 'code' => 'KAB_BOJONEGORO', 'province_id' => 14],
            ['name' => 'Kabupaten Bondowoso', 'code' => 'KAB_BONDOWOSO', 'province_id' => 14],
            ['name' => 'Kabupaten Gresik', 'code' => 'KAB_GRESIK', 'province_id' => 14],
            ['name' => 'Kabupaten Jember', 'code' => 'KAB_JEMBER', 'province_id' => 14],
            ['name' => 'Kabupaten Jombang', 'code' => 'KAB_JOMBANG', 'province_id' => 14],
            ['name' => 'Kabupaten Kediri', 'code' => 'KAB_KEDIRI', 'province_id' => 14],
            ['name' => 'Kabupaten Lamongan', 'code' => 'KAB_LAMONGAN', 'province_id' => 14],
            ['name' => 'Kabupaten Lumajang', 'code' => 'KAB_LUMAJANG', 'province_id' => 14],
            ['name' => 'Kabupaten Madiun', 'code' => 'KAB_MADIUN', 'province_id' => 14],
            ['name' => 'Kabupaten Magetan', 'code' => 'KAB_MAGETAN', 'province_id' => 14],
            ['name' => 'Kabupaten Malang', 'code' => 'KAB_MALANG', 'province_id' => 14],
            ['name' => 'Kabupaten Mojokerto', 'code' => 'KAB_MOJOKERTO', 'province_id' => 14],
            ['name' => 'Kabupaten Nganjuk', 'code' => 'KAB_NGANJUK', 'province_id' => 14],
            ['name' => 'Kabupaten Ngawi', 'code' => 'KAB_NGAWI', 'province_id' => 14],
            ['name' => 'Kabupaten Pacitan', 'code' => 'KAB_PACITAN', 'province_id' => 14],
            ['name' => 'Kabupaten Pamekasan', 'code' => 'KAB_PAMEKASAN', 'province_id' => 14],
            ['name' => 'Kabupaten Pasuruan', 'code' => 'KAB_PASURUAN', 'province_id' => 14],
            ['name' => 'Kabupaten Ponorogo', 'code' => 'KAB_PONOROGO', 'province_id' => 14],
            ['name' => 'Kabupaten Probolinggo', 'code' => 'KAB_PROBOLINGGO', 'province_id' => 14],
            ['name' => 'Kabupaten Sampang', 'code' => 'KAB_SAMPANG', 'province_id' => 14],
            ['name' => 'Kabupaten Sidoarjo', 'code' => 'KAB_SIDOARJO', 'province_id' => 14],
            ['name' => 'Kabupaten Situbondo', 'code' => 'KAB_SITUBONDO', 'province_id' => 14],
            ['name' => 'Kabupaten Sumenep', 'code' => 'KAB_SUMENEP', 'province_id' => 14],
            ['name' => 'Kabupaten Trenggalek', 'code' => 'KAB_TRENGGALEK', 'province_id' => 14],
            ['name' => 'Kabupaten Tuban', 'code' => 'KAB_TUBAN', 'province_id' => 14],
            ['name' => 'Kabupaten Tulungagung', 'code' => 'KAB_TULUNGAGUNG', 'province_id' => 14],
            ['name' => 'Kota Batu', 'code' => 'KOTA_BATU', 'province_id' => 14],
            ['name' => 'Kota Blitar', 'code' => 'KOTA_BLITAR', 'province_id' => 14],
            ['name' => 'Kota Kediri', 'code' => 'KOTA_KEDIRI', 'province_id' => 14],
            ['name' => 'Kota Madiun', 'code' => 'KOTA_MADIUN', 'province_id' => 14],
            ['name' => 'Kota Malang', 'code' => 'KOTA_MALANG', 'province_id' => 14],
            ['name' => 'Kota Mojokerto', 'code' => 'KOTA_MOJOKERTO', 'province_id' => 14],
            ['name' => 'Kota Pasuruan', 'code' => 'KOTA_PASURUAN', 'province_id' => 14],
            ['name' => 'Kota Probolinggo', 'code' => 'KOTA_PROBOLINGGO', 'province_id' => 14],
            ['name' => 'Kota Surabaya', 'code' => 'KOTA_SURABAYA', 'province_id' => 14],
            
            // Provinsi DKI Jakarta (province_id = 15)
            ['name' => 'Kota Administrasi Jakarta Barat', 'code' => 'JAKARTA_BARAT', 'province_id' => 15],
            ['name' => 'Kota Administrasi Jakarta Pusat', 'code' => 'JAKARTA_PUSAT', 'province_id' => 15],
            ['name' => 'Kota Administrasi Jakarta Selatan', 'code' => 'JAKARTA_SELATAN', 'province_id' => 15],
            ['name' => 'Kota Administrasi Jakarta Timur', 'code' => 'JAKARTA_TIMUR', 'province_id' => 15],
            ['name' => 'Kota Administrasi Jakarta Utara', 'code' => 'JAKARTA_UTARA', 'province_id' => 15],
            ['name' => 'Kabupaten Administrasi Kepulauan Seribu', 'code' => 'KEPULAUAN_SERIBU', 'province_id' => 15],
            
            // Provinsi DI Yogyakarta (province_id = 16)
            ['name' => 'Kabupaten Bantul', 'code' => 'KAB_BANTUL', 'province_id' => 16],
            ['name' => 'Kabupaten Gunungkidul', 'code' => 'KAB_GUNUNGKIDUL', 'province_id' => 16],
            ['name' => 'Kabupaten Kulon Progo', 'code' => 'KAB_KULON_PROGO', 'province_id' => 16],
            ['name' => 'Kabupaten Sleman', 'code' => 'KAB_SLEMAN', 'province_id' => 16],
            ['name' => 'Kota Yogyakarta', 'code' => 'KOTA_YOGYAKARTA', 'province_id' => 16],
            
            // Provinsi Bali (province_id = 17)
            ['name' => 'Kabupaten Badung', 'code' => 'KAB_BADUNG', 'province_id' => 17],
            ['name' => 'Kabupaten Bangli', 'code' => 'KAB_BANGLI', 'province_id' => 17],
            ['name' => 'Kabupaten Buleleng', 'code' => 'KAB_BULELENG', 'province_id' => 17],
            ['name' => 'Kabupaten Gianyar', 'code' => 'KAB_GIANYAR', 'province_id' => 17],
            ['name' => 'Kabupaten Jembrana', 'code' => 'KAB_JEMBRANA', 'province_id' => 17],
            ['name' => 'Kabupaten Karangasem', 'code' => 'KAB_KARANGASEM', 'province_id' => 17],
            ['name' => 'Kabupaten Klungkung', 'code' => 'KAB_KLUNGKUNG', 'province_id' => 17],
            ['name' => 'Kabupaten Tabanan', 'code' => 'KAB_TABANAN', 'province_id' => 17],
            ['name' => 'Kota Denpasar', 'code' => 'KOTA_DENPASAR', 'province_id' => 17],
            
            // Provinsi Nusa Tenggara Barat (province_id = 18)
            ['name' => 'Kabupaten Bima', 'code' => 'KAB_BIMA', 'province_id' => 18],
            ['name' => 'Kabupaten Dompu', 'code' => 'KAB_DOMPU', 'province_id' => 18],
            ['name' => 'Kabupaten Lombok Barat', 'code' => 'KAB_LOMBOK_BARAT', 'province_id' => 18],
            ['name' => 'Kabupaten Lombok Tengah', 'code' => 'KAB_LOMBOK_TENGAH', 'province_id' => 18],
            ['name' => 'Kabupaten Lombok Timur', 'code' => 'KAB_LOMBOK_TIMUR', 'province_id' => 18],
            ['name' => 'Kabupaten Lombok Utara', 'code' => 'KAB_LOMBOK_UTARA', 'province_id' => 18],
            ['name' => 'Kabupaten Sumbawa', 'code' => 'KAB_SUMBAWA', 'province_id' => 18],
            ['name' => 'Kabupaten Sumbawa Barat', 'code' => 'KAB_SUMBAWA_BARAT', 'province_id' => 18],
            ['name' => 'Kota Bima', 'code' => 'KOTA_BIMA', 'province_id' => 18],
            ['name' => 'Kota Mataram', 'code' => 'KOTA_MATARAM', 'province_id' => 18],
            
            // Provinsi Nusa Tenggara Timur (province_id = 19)
            ['name' => 'Kabupaten Alor', 'code' => 'KAB_ALOR', 'province_id' => 19],
            ['name' => 'Kabupaten Belu', 'code' => 'KAB_BELU', 'province_id' => 19],
            ['name' => 'Kabupaten Ende', 'code' => 'KAB_ENDE', 'province_id' => 19],
            ['name' => 'Kabupaten Flores Timur', 'code' => 'KAB_FLORES_TIMUR', 'province_id' => 19],
            ['name' => 'Kabupaten Kupang', 'code' => 'KAB_KUPANG', 'province_id' => 19],
            ['name' => 'Kabupaten Lembata', 'code' => 'KAB_LEMBATA', 'province_id' => 19],
            ['name' => 'Kabupaten Malaka', 'code' => 'KAB_MALAKA', 'province_id' => 19],
            ['name' => 'Kabupaten Manggarai', 'code' => 'KAB_MANGGARAI', 'province_id' => 19],
            ['name' => 'Kabupaten Manggarai Barat', 'code' => 'KAB_MANGGARAI_BARAT', 'province_id' => 19],
            ['name' => 'Kabupaten Manggarai Timur', 'code' => 'KAB_MANGGARAI_TIMUR', 'province_id' => 19],
            ['name' => 'Kabupaten Ngada', 'code' => 'KAB_NGADA', 'province_id' => 19],
            ['name' => 'Kabupaten Nagekeo', 'code' => 'KAB_NAGEKEO', 'province_id' => 19],
            ['name' => 'Kabupaten Rote Ndao', 'code' => 'KAB_ROTE_NDAO', 'province_id' => 19],
            ['name' => 'Kabupaten Sabu Raijua', 'code' => 'KAB_SABU_RAIJUA', 'province_id' => 19],
            ['name' => 'Kabupaten Sikka', 'code' => 'KAB_SIKKA', 'province_id' => 19],
            ['name' => 'Kabupaten Sumba Barat', 'code' => 'KAB_SUMBA_BARAT', 'province_id' => 19],
            ['name' => 'Kabupaten Sumba Barat Daya', 'code' => 'KAB_SUMBA_BARAT_DAYA', 'province_id' => 19],
            ['name' => 'Kabupaten Sumba Tengah', 'code' => 'KAB_SUMBA_TENGAH', 'province_id' => 19],
            ['name' => 'Kabupaten Sumba Timur', 'code' => 'KAB_SUMBA_TIMUR', 'province_id' => 19],
            ['name' => 'Kabupaten Timor Tengah Selatan', 'code' => 'KAB_TIMOR_TENGAH_SEL', 'province_id' => 19],
            ['name' => 'Kabupaten Timor Tengah Utara', 'code' => 'KAB_TIMOR_TENGAH_UTA', 'province_id' => 19],
            ['name' => 'Kota Kupang', 'code' => 'KOTA_KUPANG', 'province_id' => 19],
            
            // Provinsi Kalimantan Barat (province_id = 20)
            ['name' => 'Kabupaten Bengkayang', 'code' => 'KAB_BENGKAYANG', 'province_id' => 20],
            ['name' => 'Kabupaten Kapuas Hulu', 'code' => 'KAB_KAPUAS_HULU', 'province_id' => 20],
            ['name' => 'Kabupaten Kayong Utara', 'code' => 'KAB_KAYONG_UTARA', 'province_id' => 20],
            ['name' => 'Kabupaten Ketapang', 'code' => 'KAB_KETAPANG', 'province_id' => 20],
            ['name' => 'Kabupaten Kubu Raya', 'code' => 'KAB_KUBU_RAYA', 'province_id' => 20],
            ['name' => 'Kabupaten Landak', 'code' => 'KAB_LANDAK', 'province_id' => 20],
            ['name' => 'Kabupaten Melawi', 'code' => 'KAB_MELAWI', 'province_id' => 20],
            ['name' => 'Kabupaten Mempawah', 'code' => 'KAB_MEMPAWAH', 'province_id' => 20],
            ['name' => 'Kabupaten Sambas', 'code' => 'KAB_SAMBAS', 'province_id' => 20],
            ['name' => 'Kabupaten Sanggau', 'code' => 'KAB_SANGGAU', 'province_id' => 20],
            ['name' => 'Kabupaten Sekadau', 'code' => 'KAB_SEKADAU', 'province_id' => 20],
            ['name' => 'Kabupaten Sintang', 'code' => 'KAB_SINTANG', 'province_id' => 20],
            ['name' => 'Kota Pontianak', 'code' => 'KOTA_PONTIANAK', 'province_id' => 20],
            ['name' => 'Kota Singkawang', 'code' => 'KOTA_SINGKAWANG', 'province_id' => 20],
            
            // Provinsi Kalimantan Selatan (province_id = 21)
            ['name' => 'Kabupaten Balangan', 'code' => 'KAB_BALANGAN', 'province_id' => 21],
            ['name' => 'Kabupaten Banjar', 'code' => 'KAB_BANJAR', 'province_id' => 21],
            ['name' => 'Kabupaten Barito Kuala', 'code' => 'KAB_BARITO_KUALA', 'province_id' => 21],
            ['name' => 'Kabupaten Hulu Sungai Selatan', 'code' => 'KAB_HULU_SUNGAI_SEL', 'province_id' => 21],
            ['name' => 'Kabupaten Hulu Sungai Tengah', 'code' => 'KAB_HULU_SUNGAI_TEN', 'province_id' => 21],
            ['name' => 'Kabupaten Hulu Sungai Utara', 'code' => 'KAB_HULU_SUNGAI_UTA', 'province_id' => 21],
            ['name' => 'Kabupaten Kotabaru', 'code' => 'KAB_KOTABARU', 'province_id' => 21],
            ['name' => 'Kabupaten Tabalong', 'code' => 'KAB_TABALONG', 'province_id' => 21],
            ['name' => 'Kabupaten Tanah Bumbu', 'code' => 'KAB_TANAH_BUMBU', 'province_id' => 21],
            ['name' => 'Kabupaten Tanah Laut', 'code' => 'KAB_TANAH_LAUT', 'province_id' => 21],
            ['name' => 'Kabupaten Tapin', 'code' => 'KAB_TAPIN', 'province_id' => 21],
            ['name' => 'Kota Banjarbaru', 'code' => 'KOTA_BANJARBARU', 'province_id' => 21],
            ['name' => 'Kota Banjarmasin', 'code' => 'KOTA_BANJARMASIN', 'province_id' => 21],
            
            // Provinsi Kalimantan Tengah (province_id = 22)
            ['name' => 'Kabupaten Barito Selatan', 'code' => 'KAB_BARITO_SELATAN', 'province_id' => 22],
            ['name' => 'Kabupaten Barito Timur', 'code' => 'KAB_BARITO_TIMUR', 'province_id' => 22],
            ['name' => 'Kabupaten Barito Utara', 'code' => 'KAB_BARITO_UTARA', 'province_id' => 22],
            ['name' => 'Kabupaten Gunung Mas', 'code' => 'KAB_GUNUNG_MAS', 'province_id' => 22],
            ['name' => 'Kabupaten Kapuas', 'code' => 'KAB_KAPUAS', 'province_id' => 22],
            ['name' => 'Kabupaten Katingan', 'code' => 'KAB_KATINGAN', 'province_id' => 22],
            ['name' => 'Kabupaten Kotawaringin Barat', 'code' => 'KAB_KOTAWARINGIN_BAR', 'province_id' => 22],
            ['name' => 'Kabupaten Kotawaringin Timur', 'code' => 'KAB_KOTAWARINGIN_TIM', 'province_id' => 22],
            ['name' => 'Kabupaten Lamandau', 'code' => 'KAB_LAMANDAU', 'province_id' => 22],
            ['name' => 'Kabupaten Murung Raya', 'code' => 'KAB_MURUNG_RAYA', 'province_id' => 22],
            ['name' => 'Kabupaten Pulang Pisau', 'code' => 'KAB_PULANG_PISAU', 'province_id' => 22],
            ['name' => 'Kabupaten Sukamara', 'code' => 'KAB_SUKAMARA', 'province_id' => 22],
            ['name' => 'Kabupaten Seruyan', 'code' => 'KAB_SERUYAN', 'province_id' => 22],
            ['name' => 'Kota Palangka Raya', 'code' => 'KOTA_PALANGKA_RAYA', 'province_id' => 22],
            
            // Provinsi Kalimantan Timur (province_id = 23)
            ['name' => 'Kabupaten Berau', 'code' => 'KAB_BERAU', 'province_id' => 23],
            ['name' => 'Kabupaten Kutai Barat', 'code' => 'KAB_KUTAI_BARAT', 'province_id' => 23],
            ['name' => 'Kabupaten Kutai Kartanegara', 'code' => 'KAB_KUTAI_KARTANEG', 'province_id' => 23],
            ['name' => 'Kabupaten Kutai Timur', 'code' => 'KAB_KUTAI_TIMUR', 'province_id' => 23],
            ['name' => 'Kabupaten Mahakam Ulu', 'code' => 'KAB_MAHAKAM_ULU', 'province_id' => 23],
            ['name' => 'Kabupaten Paser', 'code' => 'KAB_PASER', 'province_id' => 23],
            ['name' => 'Kabupaten Penajam Paser Utara', 'code' => 'KAB_PENAJAM_PASER', 'province_id' => 23],
            ['name' => 'Kota Balikpapan', 'code' => 'KOTA_BALIKPAPAN', 'province_id' => 23],
            ['name' => 'Kota Bontang', 'code' => 'KOTA_BONTANG', 'province_id' => 23],
            ['name' => 'Kota Samarinda', 'code' => 'KOTA_SAMARINDA', 'province_id' => 23],
            
            // Provinsi Kalimantan Utara (province_id = 24)
            ['name' => 'Kabupaten Bulungan', 'code' => 'KAB_BULUNGAN', 'province_id' => 24],
            ['name' => 'Kabupaten Malinau', 'code' => 'KAB_MALINAU', 'province_id' => 24],
            ['name' => 'Kabupaten Nunukan', 'code' => 'KAB_NUNUKAN', 'province_id' => 24],
            ['name' => 'Kabupaten Tana Tidung', 'code' => 'KAB_TANA_TIDUNG', 'province_id' => 24],
            ['name' => 'Kota Tarakan', 'code' => 'KOTA_TARAKAN', 'province_id' => 24],
            
            // Provinsi Gorontalo (province_id = 25)
            ['name' => 'Kabupaten Boalemo', 'code' => 'KAB_BOALEMO', 'province_id' => 25],
            ['name' => 'Kabupaten Bone Bolango', 'code' => 'KAB_BONE_BOLANGO', 'province_id' => 25],
            ['name' => 'Kabupaten Gorontalo', 'code' => 'KAB_GORONTALO', 'province_id' => 25],
            ['name' => 'Kabupaten Gorontalo Utara', 'code' => 'KAB_GORONTALO_UTA', 'province_id' => 25],
            ['name' => 'Kabupaten Pohuwato', 'code' => 'KAB_POHUWATO', 'province_id' => 25],
            ['name' => 'Kota Gorontalo', 'code' => 'KOTA_GORONTALO', 'province_id' => 25],
            
            // Provinsi Sulawesi Selatan (province_id = 26)
            ['name' => 'Kabupaten Bantaeng', 'code' => 'KAB_BANTAENG', 'province_id' => 26],
            ['name' => 'Kabupaten Barru', 'code' => 'KAB_BARRU', 'province_id' => 26],
            ['name' => 'Kabupaten Bone', 'code' => 'KAB_BONE', 'province_id' => 26],
            ['name' => 'Kabupaten Bulukumba', 'code' => 'KAB_BULUKUMBA', 'province_id' => 26],
            ['name' => 'Kabupaten Enrekang', 'code' => 'KAB_ENREKANG', 'province_id' => 26],
            ['name' => 'Kabupaten Gowa', 'code' => 'KAB_GOWA', 'province_id' => 26],
            ['name' => 'Kabupaten Jeneponto', 'code' => 'KAB_JENEPONTO', 'province_id' => 26],
            ['name' => 'Kabupaten Kepulauan Selayar', 'code' => 'KAB_KEPULAUAN_SEL', 'province_id' => 26],
            ['name' => 'Kabupaten Luwu', 'code' => 'KAB_LUWU', 'province_id' => 26],
            ['name' => 'Kabupaten Luwu Timur', 'code' => 'KAB_LUWU_TIMUR', 'province_id' => 26],
            ['name' => 'Kabupaten Luwu Utara', 'code' => 'KAB_LUWU_UTARA', 'province_id' => 26],
            ['name' => 'Kabupaten Maros', 'code' => 'KAB_MAROS', 'province_id' => 26],
            ['name' => 'Kabupaten Pangkajene dan Kepulauan', 'code' => 'KAB_PANGKAJENE_KEP', 'province_id' => 26],
            ['name' => 'Kabupaten Pinrang', 'code' => 'KAB_PINRANG', 'province_id' => 26],
            ['name' => 'Kabupaten Sidenreng Rappang', 'code' => 'KAB_SIDENRENG_RAPP', 'province_id' => 26],
            ['name' => 'Kabupaten Sinjai', 'code' => 'KAB_SINJAI', 'province_id' => 26],
            ['name' => 'Kabupaten Soppeng', 'code' => 'KAB_SOPPENG', 'province_id' => 26],
            ['name' => 'Kabupaten Takalar', 'code' => 'KAB_TAKALAR', 'province_id' => 26],
            ['name' => 'Kabupaten Tana Toraja', 'code' => 'KAB_TANA_TORAJA', 'province_id' => 26],
            ['name' => 'Kabupaten Toraja Utara', 'code' => 'KAB_TORAJA_UTARA', 'province_id' => 26],
            ['name' => 'Kabupaten Wajo', 'code' => 'KAB_WAJO', 'province_id' => 26],
            ['name' => 'Kota Makassar', 'code' => 'KOTA_MAKASSAR', 'province_id' => 26],
            ['name' => 'Kota Palopo', 'code' => 'KOTA_PALOPO', 'province_id' => 26],
            ['name' => 'Kota Parepare', 'code' => 'KOTA_PAREPARE', 'province_id' => 26],
            
            // Provinsi Sulawesi Tenggara (province_id = 27)
            ['name' => 'Kabupaten Bombana', 'code' => 'KAB_BOMBANA', 'province_id' => 27],
            ['name' => 'Kabupaten Buton', 'code' => 'KAB_BUTON', 'province_id' => 27],
            ['name' => 'Kabupaten Buton Selatan', 'code' => 'KAB_BUTON_SELATAN', 'province_id' => 27],
            ['name' => 'Kabupaten Buton Tengah', 'code' => 'KAB_BUTON_TENGAH', 'province_id' => 27],
            ['name' => 'Kabupaten Buton Utara', 'code' => 'KAB_BUTON_UTARA', 'province_id' => 27],
            ['name' => 'Kabupaten Kolaka', 'code' => 'KAB_KOLAKA', 'province_id' => 27],
            ['name' => 'Kabupaten Kolaka Timur', 'code' => 'KAB_KOLAKA_TIMUR', 'province_id' => 27],
            ['name' => 'Kabupaten Kolaka Utara', 'code' => 'KAB_KOLAKA_UTARA', 'province_id' => 27],
            ['name' => 'Kabupaten Konawe', 'code' => 'KAB_KONAWE', 'province_id' => 27],
            ['name' => 'Kabupaten Konawe Kepulauan', 'code' => 'KAB_KONAWE_KEPUL', 'province_id' => 27],
            ['name' => 'Kabupaten Konawe Selatan', 'code' => 'KAB_KONAWE_SELATAN', 'province_id' => 27],
            ['name' => 'Kabupaten Konawe Utara', 'code' => 'KAB_KONAWE_UTARA', 'province_id' => 27],
            ['name' => 'Kabupaten Muna', 'code' => 'KAB_MUNA', 'province_id' => 27],
            ['name' => 'Kabupaten Muna Barat', 'code' => 'KAB_MUNA_BARAT', 'province_id' => 27],
            ['name' => 'Kabupaten Wakatobi', 'code' => 'KAB_WAKATOBI', 'province_id' => 27],
            ['name' => 'Kota Bau-Bau', 'code' => 'KOTA_BAU_BAU', 'province_id' => 27],
            ['name' => 'Kota Kendari', 'code' => 'KOTA_KENDARI', 'province_id' => 27],
            
            // Provinsi Sulawesi Tengah (province_id = 28)
            ['name' => 'Kabupaten Banggai', 'code' => 'KAB_BANGGAI', 'province_id' => 28],
            ['name' => 'Kabupaten Banggai Kepulauan', 'code' => 'KAB_BANGGAI_KEPUL', 'province_id' => 28],
            ['name' => 'Kabupaten Banggai Laut', 'code' => 'KAB_BANGGAI_LAUT', 'province_id' => 28],
            ['name' => 'Kabupaten Buol', 'code' => 'KAB_BUOL', 'province_id' => 28],
            ['name' => 'Kabupaten Donggala', 'code' => 'KAB_DONGGALA', 'province_id' => 28],
            ['name' => 'Kabupaten Morowali', 'code' => 'KAB_MOROWALI', 'province_id' => 28],
            ['name' => 'Kabupaten Morowali Utara', 'code' => 'KAB_MOROWALI_UTARA', 'province_id' => 28],
            ['name' => 'Kabupaten Parigi Moutong', 'code' => 'KAB_PARIGI_MOUTONG', 'province_id' => 28],
            ['name' => 'Kabupaten Poso', 'code' => 'KAB_POSO', 'province_id' => 28],
            ['name' => 'Kabupaten Sigi', 'code' => 'KAB_SIGI', 'province_id' => 28],
            ['name' => 'Kabupaten Tojo Una-Una', 'code' => 'KAB_TOJO_UNA_UNA', 'province_id' => 28],
            ['name' => 'Kabupaten Toli-Toli', 'code' => 'KAB_TOLI_TOLI', 'province_id' => 28],
            ['name' => 'Kota Palu', 'code' => 'KOTA_PALU', 'province_id' => 28],
            
            // Provinsi Sulawesi Utara (province_id = 29)
            ['name' => 'Kabupaten Bolaang Mongondow', 'code' => 'KAB_BOLAANG_MONGON', 'province_id' => 29],
            ['name' => 'Kabupaten Bolaang Mongondow Selatan', 'code' => 'KAB_BOLAANG_SEL', 'province_id' => 29],
            ['name' => 'Kabupaten Bolaang Mongondow Timur', 'code' => 'KAB_BOLAANG_TIM', 'province_id' => 29],
            ['name' => 'Kabupaten Bolaang Mongondow Utara', 'code' => 'KAB_BOLAANG_UTA', 'province_id' => 29],
            ['name' => 'Kabupaten Kepulauan Sangihe', 'code' => 'KAB_KEPULAUAN_SANG', 'province_id' => 29],
            ['name' => 'Kabupaten Kepulauan Siau Tagulandang Biaro', 'code' => 'KAB_KEPULAUAN_SIAU', 'province_id' => 29],
            ['name' => 'Kabupaten Kepulauan Talaud', 'code' => 'KAB_KEPULAUAN_TALA', 'province_id' => 29],
            ['name' => 'Kabupaten Minahasa', 'code' => 'KAB_MINAHASA', 'province_id' => 29],
            ['name' => 'Kabupaten Minahasa Selatan', 'code' => 'KAB_MINAHASA_SELAT', 'province_id' => 29],
            ['name' => 'Kabupaten Minahasa Tenggara', 'code' => 'KAB_MINAHASA_TENG', 'province_id' => 29],
            ['name' => 'Kabupaten Minahasa Utara', 'code' => 'KAB_MINAHASA_UTARA', 'province_id' => 29],
            ['name' => 'Kota Bitung', 'code' => 'KOTA_BITUNG', 'province_id' => 29],
            ['name' => 'Kota Kotamobagu', 'code' => 'KOTA_KOTAMOBAGU', 'province_id' => 29],
            ['name' => 'Kota Manado', 'code' => 'KOTA_MANADO', 'province_id' => 29],
            ['name' => 'Kota Tomohon', 'code' => 'KOTA_TOMOHON', 'province_id' => 29],
            
            // Provinsi Maluku (province_id = 30)
            ['name' => 'Kabupaten Buru', 'code' => 'KAB_BURU', 'province_id' => 30],
            ['name' => 'Kabupaten Buru Selatan', 'code' => 'KAB_BURU_SELATAN', 'province_id' => 30],
            ['name' => 'Kabupaten Kepulauan Aru', 'code' => 'KAB_KEPULAUAN_ARU', 'province_id' => 30],
            ['name' => 'Kabupaten Maluku Barat Daya', 'code' => 'KAB_MALUKU_BARAT', 'province_id' => 30],
            ['name' => 'Kabupaten Maluku Tengah', 'code' => 'KAB_MALUKU_TENGAH', 'province_id' => 30],
            ['name' => 'Kabupaten Maluku Tenggara', 'code' => 'KAB_MALUKU_TENGG', 'province_id' => 30],
            ['name' => 'Kabupaten Maluku Tenggara Barat', 'code' => 'KAB_MALUKU_TENG_B', 'province_id' => 30],
            ['name' => 'Kabupaten Seram Bagian Barat', 'code' => 'KAB_SERAM_BAG_BAR', 'province_id' => 30],
            ['name' => 'Kabupaten Seram Bagian Timur', 'code' => 'KAB_SERAM_BAG_TIM', 'province_id' => 30],
            ['name' => 'Kota Ambon', 'code' => 'KOTA_AMBON', 'province_id' => 30],
            ['name' => 'Kota Tual', 'code' => 'KOTA_TUAL', 'province_id' => 30],
            
            // Provinsi Maluku Utara (province_id = 31)
            ['name' => 'Kabupaten Halmahera Barat', 'code' => 'KAB_HALMAHERA_BAR', 'province_id' => 31],
            ['name' => 'Kabupaten Halmahera Tengah', 'code' => 'KAB_HALMAHERA_TEN', 'province_id' => 31],
            ['name' => 'Kabupaten Halmahera Utara', 'code' => 'KAB_HALMAHERA_UTA', 'province_id' => 31],
            ['name' => 'Kabupaten Halmahera Selatan', 'code' => 'KAB_HALMAHERA_SEL', 'province_id' => 31],
            ['name' => 'Kabupaten Kepulauan Sula', 'code' => 'KAB_KEPULAUAN_SULA', 'province_id' => 31],
            ['name' => 'Kabupaten Halmahera Timur', 'code' => 'KAB_HALMAHERA_TIM', 'province_id' => 31],
            ['name' => 'Kabupaten Pulau Morotai', 'code' => 'KAB_PULAU_MOROTAI', 'province_id' => 31],
            ['name' => 'Kabupaten Pulau Taliabu', 'code' => 'KAB_PULAU_TALIABU', 'province_id' => 31],
            ['name' => 'Kota Ternate', 'code' => 'KOTA_TERNATE', 'province_id' => 31],
            ['name' => 'Kota Tidore Kepulauan', 'code' => 'KOTA_TIDORE_KEPUL', 'province_id' => 31],
            
            // Provinsi Papua (province_id = 32)
            ['name' => 'Kabupaten Asmat', 'code' => 'KAB_ASMAT', 'province_id' => 32],
            ['name' => 'Kabupaten Biak Numfor', 'code' => 'KAB_BIAK_NUMFOR', 'province_id' => 32],
            ['name' => 'Kabupaten Boven Digoel', 'code' => 'KAB_BOVEN_DIGOEL', 'province_id' => 32],
            ['name' => 'Kabupaten Deiyai', 'code' => 'KAB_DEIYAI', 'province_id' => 32],
            ['name' => 'Kabupaten Dogiyai', 'code' => 'KAB_DOGIYAI', 'province_id' => 32],
            ['name' => 'Kabupaten Intan Jaya', 'code' => 'KAB_INTAN_JAYA', 'province_id' => 32],
            ['name' => 'Kabupaten Jayapura', 'code' => 'KAB_JAYAPURA', 'province_id' => 32],
            ['name' => 'Kabupaten Jayawijaya', 'code' => 'KAB_JAYAWIJAYA', 'province_id' => 32],
            ['name' => 'Kabupaten Keerom', 'code' => 'KAB_KEEROM', 'province_id' => 32],
            ['name' => 'Kabupaten Kepulauan Yapen', 'code' => 'KAB_KEPULAUAN_YAPE', 'province_id' => 32],
            ['name' => 'Kabupaten Lanny Jaya', 'code' => 'KAB_LANNY_JAYA', 'province_id' => 32],
            ['name' => 'Kabupaten Mamberamo Raya', 'code' => 'KAB_MAMBERAMO_RAYA', 'province_id' => 32],
            ['name' => 'Kabupaten Mamberamo Tengah', 'code' => 'KAB_MAMBERAMO_TEN', 'province_id' => 32],
            ['name' => 'Kabupaten Mappi', 'code' => 'KAB_MAPPI', 'province_id' => 32],
            ['name' => 'Kabupaten Merauke', 'code' => 'KAB_MERAUKE', 'province_id' => 32],
            ['name' => 'Kabupaten Mimika', 'code' => 'KAB_MIMIKA', 'province_id' => 32],
            ['name' => 'Kabupaten Nabire', 'code' => 'KAB_NABIRE', 'province_id' => 32],
            ['name' => 'Kabupaten Nduga', 'code' => 'KAB_NDUGA', 'province_id' => 32],
            ['name' => 'Kabupaten Paniai', 'code' => 'KAB_PANIAI', 'province_id' => 32],
            ['name' => 'Kabupaten Pegunungan Bintang', 'code' => 'KAB_PEGUNUNGAN_BIN', 'province_id' => 32],
            ['name' => 'Kabupaten Puncak', 'code' => 'KAB_PUNCAK', 'province_id' => 32],
            ['name' => 'Kabupaten Puncak Jaya', 'code' => 'KAB_PUNCAK_JAYA', 'province_id' => 32],
            ['name' => 'Kabupaten Sarmi', 'code' => 'KAB_SARMI', 'province_id' => 32],
            ['name' => 'Kabupaten Supiori', 'code' => 'KAB_SUPIORI', 'province_id' => 32],
            ['name' => 'Kabupaten Tolikara', 'code' => 'KAB_TOLIKARA', 'province_id' => 32],
            ['name' => 'Kabupaten Waropen', 'code' => 'KAB_WAROPEN', 'province_id' => 32],
            ['name' => 'Kabupaten Yahukimo', 'code' => 'KAB_YAHUKIMO', 'province_id' => 32],
            ['name' => 'Kabupaten Yalimo', 'code' => 'KAB_YALIMO', 'province_id' => 32],
            ['name' => 'Kota Jayapura', 'code' => 'KOTA_JAYAPURA', 'province_id' => 32],
            
            // Provinsi Papua Barat (province_id = 33)
            ['name' => 'Kabupaten Fakfak', 'code' => 'KAB_FAKFAK', 'province_id' => 33],
            ['name' => 'Kabupaten Kaimana', 'code' => 'KAB_KAIMANA', 'province_id' => 33],
            ['name' => 'Kabupaten Manokwari', 'code' => 'KAB_MANOKWARI', 'province_id' => 33],
            ['name' => 'Kabupaten Manokwari Selatan', 'code' => 'KAB_MANOKWARI_SEL', 'province_id' => 33],
            ['name' => 'Kabupaten Maybrat', 'code' => 'KAB_MAYBRAT', 'province_id' => 33],
            ['name' => 'Kabupaten Pegunungan Arfak', 'code' => 'KAB_PEGUNUNGAN_ARF', 'province_id' => 33],
            ['name' => 'Kabupaten Raja Ampat', 'code' => 'KAB_RAJA_AMPAT', 'province_id' => 33],
            ['name' => 'Kabupaten Sorong', 'code' => 'KAB_SORONG', 'province_id' => 33],
            ['name' => 'Kabupaten Sorong Selatan', 'code' => 'KAB_SORONG_SELATAN', 'province_id' => 33],
            ['name' => 'Kabupaten Tambrauw', 'code' => 'KAB_TAMBRAUW', 'province_id' => 33],
            ['name' => 'Kabupaten Teluk Bintuni', 'code' => 'KAB_TELUK_BINTUNI', 'province_id' => 33],
            ['name' => 'Kabupaten Teluk Wondama', 'code' => 'KAB_TELUK_WONDAMA', 'province_id' => 33],
        ];

        foreach ($regencies as $regency) {
            \App\Models\Regency::create($regency);
        }
    }

}